<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="60809" started-at="2018-03-16T20:29:47Z" finished-at="2018-03-16T20:30:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="60809" started-at="2018-03-16T20:29:47Z" finished-at="2018-03-16T20:30:48Z">
      <class name="com.globant.automation.EngineCompare">
        <test-method status="PASS" signature="prepareClass()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="prepareClass" is-config="true" duration-ms="1511" started-at="2018-03-16T20:29:47Z" finished-at="2018-03-16T20:29:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepareClass -->
        <test-method status="PASS" signature="prepareTest()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="prepareTest" is-config="true" duration-ms="1739" started-at="2018-03-16T20:29:48Z" finished-at="2018-03-16T20:29:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepareTest -->
        <test-method status="FAIL" signature="searchTest(java.lang.String)[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="searchTest" duration-ms="10240" started-at="2018-03-16T20:29:50Z" data-provider="Search" finished-at="2018-03-16T20:30:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Pink Floyd]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Pink Floyd - YouTube] but found [Pink Floyd - Wikipedia, la enciclopedia libre]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Pink Floyd - YouTube] but found [Pink Floyd - Wikipedia, la enciclopedia libre]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.globant.automation.EngineCompare.searchTest(EngineCompare.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="cleanup()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="cleanup" is-config="true" duration-ms="76" started-at="2018-03-16T20:30:00Z" finished-at="2018-03-16T20:30:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method status="PASS" signature="prepareTest()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="prepareTest" is-config="true" duration-ms="1823" started-at="2018-03-16T20:30:01Z" finished-at="2018-03-16T20:30:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepareTest -->
        <test-method status="FAIL" signature="searchTest(java.lang.String)[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="searchTest" duration-ms="9777" started-at="2018-03-16T20:30:02Z" data-provider="Search" finished-at="2018-03-16T20:30:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Led Zeppelin]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Led Zeppelin, II, III, IV, Houses of the …] but found [Led Zeppelin - Wikipedia, la enciclopedia libre]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Led Zeppelin, II, III, IV, Houses of the …] but found [Led Zeppelin - Wikipedia, la enciclopedia libre]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.globant.automation.EngineCompare.searchTest(EngineCompare.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="cleanup()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="cleanup" is-config="true" duration-ms="72" started-at="2018-03-16T20:30:12Z" finished-at="2018-03-16T20:30:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method status="PASS" signature="prepareTest()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="prepareTest" is-config="true" duration-ms="1177" started-at="2018-03-16T20:30:12Z" finished-at="2018-03-16T20:30:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepareTest -->
        <test-method status="FAIL" signature="searchTest(java.lang.String)[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="searchTest" duration-ms="8406" started-at="2018-03-16T20:30:13Z" data-provider="Search" finished-at="2018-03-16T20:30:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[The Beatles]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The Beatles] but found [The Beatles - Wikipedia, la enciclopedia libre]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The Beatles] but found [The Beatles - Wikipedia, la enciclopedia libre]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.globant.automation.EngineCompare.searchTest(EngineCompare.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="cleanup()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="cleanup" is-config="true" duration-ms="71" started-at="2018-03-16T20:30:22Z" finished-at="2018-03-16T20:30:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method status="PASS" signature="prepareTest()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="prepareTest" is-config="true" duration-ms="527" started-at="2018-03-16T20:30:22Z" finished-at="2018-03-16T20:30:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepareTest -->
        <test-method status="FAIL" signature="searchTest(java.lang.String)[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="searchTest" duration-ms="9068" started-at="2018-03-16T20:30:22Z" data-provider="Search" finished-at="2018-03-16T20:30:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Tame Impala]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Tame Impala - Elephant - YouTube] but found [Tame Impala - Wikipedia, la enciclopedia libre]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Tame Impala - Elephant - YouTube] but found [Tame Impala - Wikipedia, la enciclopedia libre]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.globant.automation.EngineCompare.searchTest(EngineCompare.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="cleanup()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="cleanup" is-config="true" duration-ms="73" started-at="2018-03-16T20:30:31Z" finished-at="2018-03-16T20:30:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method status="PASS" signature="prepareTest()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="prepareTest" is-config="true" duration-ms="653" started-at="2018-03-16T20:30:32Z" finished-at="2018-03-16T20:30:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepareTest -->
        <test-method status="FAIL" signature="searchTest(java.lang.String)[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="searchTest" duration-ms="15413" started-at="2018-03-16T20:30:32Z" data-provider="Search" finished-at="2018-03-16T20:30:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Pond]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Pond - Wikipedia] but found [pond - English-Spanish Dictionary - WordReference.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Pond - Wikipedia] but found [pond - English-Spanish Dictionary - WordReference.com]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.globant.automation.EngineCompare.searchTest(EngineCompare.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="cleanup()[pri:0, instance:com.globant.automation.EngineCompare@5b239d7d]" name="cleanup" is-config="true" duration-ms="136" started-at="2018-03-16T20:30:48Z" finished-at="2018-03-16T20:30:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- com.globant.automation.EngineCompare -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
